### PR TITLE
Direct share/copy link on toolbar

### PR DESCRIPTION
**Pull request by morandat**

### CODE REVIEW

**Comment by francoisschwarzentruber** [comment]
Excellent! Thank you very much for your contribution. Very useful for people that quickly want to discuss together (click!). 
Teachers can still of course do the loooong procedure ``Menu, Share, Type a password, Share, Copy''.

**Comment by francoisschwarzentruber** [comment]
Thank you! But something is not clear in the actual repository. It is the Typescript files that have to modified, not the JS ones that are generated by tsc (the Typescript compiler). I do not know how to remove the JS file so that the github.io still works, so the repository contains... both the source files in TS, and the generated ones in JS. Do you have a idea?

**Comment by morandat** [comment]
Ohhh I haven't notice at ill it was ts.
From my point of view you have to remove the `js` dir (voiding thus my contrib but no worry) from git ; use a build system (pick one compatible with github). Add an action in github to package the `js` in a ugly big one js file ;)

**Comment by morandat** [comment]
> Ohhh I haven't notice at ill it was ts.
This explains a lot ;)

**Comment by francoisschwarzentruber** [comment]
Your contribution is not voided at all: I have included it in the TS code. :) Thank you! I will try to find how to proceed at some point. At the moment, I do not know where to find a "build system", and where to add an "action".

**Comment by morandat** [comment]
npm may be used as build tool maybe i'll give it a try.

**Comment by francoisschwarzentruber** [comment]
OK! Oh, there is a bug in the Copy the link button. Maybe, I did not fix properly. As you better know the function you wrote, if you want to, could you fix it by modifying share.ts?

**Comment by morandat** [comment]
I have a lecture this afternoon, but I'll have a look.

**Pull request merged**
